defaults:
  - base

name: flw_dataset
path: /media/admin_flw/Volume/TUD_Thesis/LEOD/datasets/FLW_Dataset_19-11-24
ev_repr_name: 'stacked_histogram_dt=50_nbins=10'
sequence_length: 21
resolution_hw: [480, 640]
downsample_by_factor_2: False
only_load_end_labels: False

train_ratio: 0.64
test_ratio: 0.22
val_ratio: 0.14

# time-flip data augmentation
data_augmentation:
  random:
     prob_hflip: 0.5
     prob_tflip: 0.5
  stream:
    prob_hflip: 0.4
    prob_tflip: 0.5
